<a href="https://colab.research.google.com/github/prabal5ghosh/UCA-M2-SEMESTER1/blob/main/deep%20learning/Lecture3_TP_manual_backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1>TP: Manual backprop</h1></center>

# Warning :
# "File -> Save a copy in Drive" before starting to modify the notebook, otherwise changes won't be saved.


In [1]:
!wget https://remysun.github.io/uploads/TPBackprop.zip
!unzip -j TPBackprop.zip
!wget https://remysun.github.io/uploads/utils-data.py

--2024-10-15 13:48:56--  https://remysun.github.io/uploads/TPBackprop.zip
Resolving remysun.github.io (remysun.github.io)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to remysun.github.io (remysun.github.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13423382 (13M) [application/zip]
Saving to: ‘TPBackprop.zip’

TPBackprop.zip      100%[===================>]  12.80M  --.-KB/s    in 0.09s   

2024-10-15 13:48:57 (142 MB/s) - ‘TPBackprop.zip’ saved [13423382/13423382]

Archive:  TPBackprop.zip
  inflating: ._TP3-4                 
  inflating: circles.mat             
  inflating: ._circles.mat           
  inflating: mnist.mat               
  inflating: ._mnist.mat             
--2024-10-15 13:48:57--  https://remysun.github.io/uploads/utils-data.py
Resolving remysun.github.io (remysun.github.io)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to remysun.github.io (remysun.github.io)|185.199.108.

In [7]:
import math
import torch
from torch.autograd import Variable
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %run 'utils-data.py'

# Part 1 : Forward et Backward

Complete the function init_params to initialize the weights and store them in a dictionary. All weights should be initialized following a normal law with mean 0 and standard deviation 0.3.
Hint: Use torch.randn and torch.zeros

In [8]:
def init_params(nx, nh, ny):
    """
    nx, nh, ny: integers
    out params: dictionnary
    """
    params = {}

    #####################
    ## Votre code ici  ##
    #####################
    # remplir avec les paramètres Wh, Wy, bh, by

    params["Wh"] = torch.randn(nx,nh)*0.3
    params["Wy"] = torch.randn(nh,ny)*0.3
    params["bh"] = torch.zeros(nh)
    params["by"] = torch.zeros(ny)

    ####################
    ##      FIN        #
    ####################
    return params

Complete the function forward to compute all the intermediary activations and the final output of the network given a batch of inputs X along with network weights params. The function should return a dictionary of intermediate steps and the output Y of the network.
Hint: torch.mm implements matricial multiplication and torch.tanh, torch.exp, and torch.sum give useful functions.

In [20]:
params = init_params(2,4,4)

In [21]:
params

{'Wh': tensor([[-0.1795, -0.0806,  0.0544,  0.2377],
         [-0.1141, -0.4611, -0.1802,  0.3391]]),
 'Wy': tensor([[ 0.1644, -0.5525,  0.5397, -0.0872],
         [-0.0494,  0.6969, -0.5034,  0.3467],
         [ 0.1103,  0.2610, -0.0564, -0.0442],
         [-0.1534,  0.0746, -0.1625,  0.3523]]),
 'bh': tensor([0., 0., 0., 0.]),
 'by': tensor([0., 0., 0., 0.])}

In [43]:
def forward(params, X):
    """
    params: dictionnary
    X: (n_batch, dimension)
    """
#     bsize = X.size(0)
    bsize = X.size

    nh = params['Wh'].size(0)
    ny = params['Wy'].size(0)
    outputs = {}

    #####################
    ## Votre code ici  ##
    #####################
    # remplir avec les paramètres X, htilde, h, ytilde, yhat

    outputs["X"] = X
    print(X)
    print(params["Wh"])
    print(params["bh"])
    print(torch.mm(X,params["Wh"]. T))
    
    
    outputs["htilde"] = torch.mm(X,params["Wh"]. T) + params["bh"]
    outputs["h"] = torch.tanh(outputs["htilde"])
    outputs["ytilde"] = torch.mm(outputs["h"],params["Wy"].T ) + params["by"]
    # outputs["yhat"] = torch.nn.functional.softmax(input = outputs["ytilde"])
    x_exp = torch.exp(outputs["ytilde"])
    x_exp_sum = torch.sum(x_exp, 1, keepdim=True)
    outputs["yhat"] =x_exp/x_exp_sum

    ####################
    ##      FIN        #
    ####################

    return outputs['yhat'], outputs

In [44]:
params

{'Wh': tensor([[-0.1795, -0.0806,  0.0544,  0.2377],
         [-0.1141, -0.4611, -0.1802,  0.3391]]),
 'Wy': tensor([[ 0.1644, -0.5525,  0.5397, -0.0872],
         [-0.0494,  0.6969, -0.5034,  0.3467],
         [ 0.1103,  0.2610, -0.0564, -0.0442],
         [-0.1534,  0.0746, -0.1625,  0.3523]]),
 'bh': tensor([0., 0., 0., 0.]),
 'by': tensor([0., 0., 0., 0.])}

Complete loss_accuracy to compute the cost function and the accuracy of the model from a matrix Yhat of outputs with respect to a ground truth matrix Y, and return the loss and accuracy.
Note: You should use the function _, indsY = torch.max(Y,1) to get the index of the predicted class for each sample.
Hint: You might want to use torch.mean, torch.max, torch.log and torch.sum.

In [45]:
predictions = forward(params,torch.tensor(np.array([[0.0,0.0,0.0,1.0]])))

tensor([[0., 0., 0., 1.]], dtype=torch.float64)
tensor([[-0.1795, -0.0806,  0.0544,  0.2377],
        [-0.1141, -0.4611, -0.1802,  0.3391]])
tensor([0., 0., 0., 0.])


RuntimeError: expected m1 and m2 to have the same dtype, but got: double != float

In [11]:
import numpy as np

def cross_entropy(predictions, targets, epsilon = 1e-10):
    # epsilon is added for numerical stability
    predictions = np.clip(predictions, epsilon, 1.0- epsilon)
    N= predictions.shape[0]
    ce_loss = -np.sum(np.sum(targets * np.log(predictions+ 1e-5)))/ N
    return ce_loss

In [12]:
# predictions = np.array([[0.00,0.00,0.40,0.60],[0.01,0.01,0.01,0.96]])
# targets = np.array([[0,0,0,1],[0,0,0,1]])

In [13]:
# cross_entropy(predictions, targets)

In [13]:
def loss_accuracy(Yhat, Y):

    #####################
    ## Votre code ici  ##
    #####################

    L = torch.nn.functional.cross_entropy(input= Yhat, target = Y)
    acc = torch.sum(Yhat == Y)

    ####################
    ##      FIN        #
    ####################

    return L, acc

Complete the backward function to compute the loss gradients with respect to the parameters, and store these gradients into the output dictionary.

In [ ]:
def backward(params, outputs, Y):
    bsize = Y.shape[0]
    grads = {}

    #####################
    ## Votre code ici  ##
    #####################
    # remplir avec les paramètres Wy, Wh, by, bh

    grads["Wy"] = None
    grads["Wh"] = None
    grads["by"] = None
    grads["bh"] = None

    ####################
    ##      FIN        #
    ####################
    return grads

Now apply the SGD steps in the sgd function to update the parameters given the computed gradients.

In [ ]:
def sgd(params, grads, eta):

    #####################
    ## Votre code ici  ##
    #####################
    # mettre à jour le contenu de params

    params["Wh"] = None
    params["Wy"] = None
    params["bh"] = None
    params["by"] = None

    ####################
    ##      FIN        #
    ####################
    return params

## Algorithme global d'apprentissage (manuel)

Fill in the forward, backward and SGD update calls in the training loop.
Hint: The running batches Xtrain and Ytrain are already prepared for you in the code!

In [ ]:
# init
data = CirclesData()
data.plot_data()
N = data.Xtrain.shape[0]
Nbatch = 10
nx = data.Xtrain.shape[1]
nh = 10
ny = data.Ytrain.shape[1]
eta = 0.03

params = init_params(nx, nh, ny)

curves = [[],[], [], []]

# epoch
for iteration in range(150):

    # permute
    perm = np.random.permutation(N)
    Xtrain = data.Xtrain[perm, :]
    Ytrain = data.Ytrain[perm, :]

    #####################
    ## Votre code ici  ##
    #####################
    # batches
    for j in range(N // Nbatch):

        indsBatch = range(j * Nbatch, (j+1) * Nbatch)
        X = Xtrain[indsBatch, :]
        Y = Ytrain[indsBatch, :]

        # écrire l'algorithme d'apprentissage sur le batch (X,Y)
        # en utilisant les fonctions forward, loss_accuracy, backward, sgd


    ####################
    ##      FIN        #
    ####################


    Yhat_train, _ = forward(params, data.Xtrain)
    Yhat_test, _ = forward(params, data.Xtest)
    Ltrain, acctrain = loss_accuracy(Yhat_train, data.Ytrain)
    Ltest, acctest = loss_accuracy(Yhat_test, data.Ytest)
    Ygrid, _ = forward(params, data.Xgrid)

    title = 'Iter {}: Acc train {:.1f}% ({:.2f}), acc test {:.1f}% ({:.2f})'.format(iteration, acctrain, Ltrain, acctest, Ltest)
    print(title)
    data.plot_data_with_grid(Ygrid, title)

    curves[0].append(acctrain)
    curves[1].append(acctest)
    curves[2].append(Ltrain)
    curves[3].append(Ltest)

fig = plt.figure()
plt.plot(curves[0], label="acc. train")
plt.plot(curves[1], label="acc. test")
plt.plot(curves[2], label="loss train")
plt.plot(curves[3], label="loss test")
plt.legend()
plt.show()

# Bonus: Try to add a third layer to the MLP!